### ISSUE TITLE
Issues on scikit-xray tutorial

### ISSUE THREAD

**Issue by licode** [scikit-xray/scikit-xray#329]
We have several demo in scikit-xray examples, https://github.com/scikit-xray/scikit-xray-examples/tree/master/demos. Can we also link them through scikit-xray doc http://scikit-xray.github.io/scikit-xray/?

**Comment by sameera2004** [comment]
Yes it is a good idea!

**Comment by licode** [comment]
@danielballan will take care of this during the weekend?

**Comment by danielballan** [comment]
Yes, I'm on it. Fighting the good fight over here...

**Comment by danielballan** [comment]
@licode @sameera2004 I generated .rst files from the notebooks and added links to index.html under the "Tutorial" heading.

It's a start, but as you can see it looks ugly right now because sphinx has generated many links for each notebook.

Here's how we can fix that: sphinx automatically generates links into the notebook by looking for top-level headings (meaning `<h1>` in HTML terms) and generating a link for each one. In trackpy, we use one top-level heading at the top of the notebook. We use sub-headings for everything else.

```
# This is a top-level heading, like the title of the notebook
## This is a sub-heading
### This is a smaller sub-heading
``
It looks like some or all of you have been using top-level heading liberally. If you change all but the title to subheadings, using two or more pound signs as above, the look of the main page will improve.

**Comment by danielballan** [comment]
Link to our docs:  http://scikit-xray.github.io/scikit-xray
Link to trackpy docs, using the same pattern but with one top-level heading per notebook: http://soft-matter.github.io/trackpy/

**Comment by ericdill** [comment]
Oh man that's my bad for using headings in a stupid way. I'll fix that

**Comment by licode** [comment]
Thanks. The trackpy doc looks awesome. I think we are getting there after some minor fix.

**Comment by sameera2004** [comment]
Thanks,  yes trackpy docs looks really good, sure I will only put one top-level heading in the future notebook,

**Comment by danielballan** [comment]
Let's fix the old ones too.
